"""empty message

Revision ID: 38e2d8fe0957
Revises: 1ea6b88185f8
Create Date: 2023-09-29 13:01:03.609785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e2d8fe0957'
down_revision = '1ea6b88185f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('test_name', sa.String(length=128), nullable=True),
    sa.Column('due_date', sa.String(length=128), nullable=True),
    sa.Column('number_of_questions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
