"""recreate

Revision ID: 6431124a6a89
Revises: 
Create Date: 2023-09-18 01:11:28.532760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6431124a6a89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('fk_test_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fk_test_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('self_evaluation', sa.Integer(), nullable=True),
    sa.Column('teacher_evaluation', sa.Integer(), nullable=True),
    sa.Column('program_evaluation', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.test_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('test')
    op.drop_table('user')
    # ### end Alembic commands ###
