"""empty message

Revision ID: 798dedc3ba63
Revises: 38e2d8fe0957
Create Date: 2023-09-29 13:06:52.355450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798dedc3ba63'
down_revision = '38e2d8fe0957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_name', sa.String(length=128), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
