"""add difficulty field to each question

Revision ID: 8155d1d0899d
Revises: b500f4976e35
Create Date: 2023-09-20 15:29:19.423609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8155d1d0899d'
down_revision = 'b500f4976e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
