"""move feedback field to Test

Revision ID: b500f4976e35
Revises: d7f1a3539a51
Create Date: 2023-09-18 12:22:10.337284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b500f4976e35'
down_revision = 'd7f1a3539a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
